[package]
name = "epoll"
version = "0.1.0"
edition = "2021"


[dependencies]
libc = "0.2"
reqwest = { version = "*", features = ["json"] }
tokio = { version = "*", features = ["full"] }
serde_json = "1.0"
openssl-sys = "0.9.75"
